In [1]:
import numpy as np

In [5]:
np.array([1, 0, 3], bool)

array([ True, False,  True], dtype=bool)

Данный Notebook дает представление об использовании и применении модуля NumPy


Ссылка на документацию https://docs.scipy.org/doc/numpy/user/quickstart.html#prerequisites

In [21]:
from numpy import *

После подключения библиотеки рассмотрим основные способы инициализации массива numpy

Инициализация производится следующим образом array([список элементов],тип данных)

In [22]:
a=array([1,2,3*pi])

In [23]:
a

array([1.        , 2.        , 9.42477796])

In [24]:
a=array([1,2,3*pi],int)

In [25]:
a

array([1, 2, 9])

In [26]:
c=array([[1,2,3],[4,5,6],[7,8],[9,10]])

In [27]:
c

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8]), list([9, 10])],
      dtype=object)

В Python NumPy есть возможность задавать специальные массивы. Такими массивами являются единичные матрица либо матрицы, заполненные нулями или единицами

In [28]:
zeros(5,int)

array([0, 0, 0, 0, 0])

In [29]:
zeros(5,complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [30]:
ones((2,6),complex)

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [31]:
identity(6,int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

В Python есть возможность задавать диапазоны значений, используя библиотеку NumPy. Для этого есть функции arange, linspace, logspace. Необходимые параметры: arange (от, до, шаг,тип данных). linspace(первый элемент, последний элемент, размерность). logspace (первый элемент, последний элемент, размерность)

In [32]:
arange(1,9,3,float)

array([1., 4., 7.])

In [33]:
linspace(2,12,6)

array([ 2.,  4.,  6.,  8., 10., 12.])

In [34]:
logspace(0,1,3)

array([ 1.        ,  3.16227766, 10.        ])

Numpy богата методами, позволяющими реализовывать различные операции над матрицами, массивами. 

Рассмотрим первую операцию, операцию простой индексации

In [35]:
m=array([[11,12,13,14],
        [21,22,23,24],
        [31,32,33,34]])

In [36]:
m

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [37]:
m[1]

array([21, 22, 23, 24])

In [38]:
m[1][1]

22

В Python Numpy есть возможность брать сечения, срезы массивов. Синтаксис следующий: от:до или от:до:шаг

In [39]:
m[1][0:3]

array([21, 22, 23])

In [40]:
m[0][::2]

array([11, 13])

Следующие операции над матрицами, доступные в Numpy являются операции взятия размера матрицы, ее формы, а также транспонирование матрицы

In [41]:
c=array([[11,12,13],[21,22,23]])

In [42]:
c

array([[11, 12, 13],
       [21, 22, 23]])

In [43]:
c.size

6

In [44]:
c.shape

(2, 3)

In [45]:
c.reshape(3,2)

array([[11, 12],
       [13, 21],
       [22, 23]])

In [46]:
c

array([[11, 12, 13],
       [21, 22, 23]])

In [47]:
transpose(c)

array([[11, 21],
       [12, 22],
       [13, 23]])

In [48]:
transpose(c.reshape(1,6))

array([[11],
       [12],
       [13],
       [21],
       [22],
       [23]])

В Numpy есть фозможность преобразования матриц любых размерностей в одномерную с помощью операции ravel


In [49]:
c

array([[11, 12, 13],
       [21, 22, 23]])

In [50]:
c.ravel()

array([11, 12, 13, 21, 22, 23])

In [51]:
ravel(transpose(c.reshape(1,6)))

array([11, 12, 13, 21, 22, 23])

In [52]:
resize(c,10)

array([11, 12, 13, 21, 22, 23, 11, 12, 13, 21])

Также в Numpy есть возможность склеивания двух массивов между собой с помощью функций hstack и vstack

In [53]:
a=array([[1,2,3],[4,5,6]])

In [54]:
b=array([[10,20,30],[40,50,60]])

In [55]:
c=array([[100,200],[400,500]])

In [56]:
vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [57]:
hstack((a,b,c))

array([[  1,   2,   3,  10,  20,  30, 100, 200],
       [  4,   5,   6,  40,  50,  60, 400, 500]])

Также возможно размножить значение на необходимую размерность массива

In [58]:
tile(pi,(4,6))

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265]])

In [59]:
tile([2,3],(2,2))

array([[2, 3, 2, 3],
       [2, 3, 2, 3]])

ПОКОМПОНЕНТНЫЕ ОПЕРАЦИИ НАД МАССИВАМИ

Массивы одинаковой размерности

In [60]:
a=array([[1,2,3],[4,5,6]])

In [61]:
b=array([[1,1,1],[2,2,2]])

In [62]:
a+b


array([[2, 3, 4],
       [6, 7, 8]])

In [63]:
a**b

array([[ 1,  2,  3],
       [16, 25, 36]])

In [64]:
a*b

array([[ 1,  2,  3],
       [ 8, 10, 12]])

Если размерности разные

In [65]:
a=zeros((3,4),int)

In [66]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
a+15

array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]])

In [68]:
b=array([1,2,3,4])

In [69]:
a+b

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [70]:
c=array([[1],[2],[3]])

In [71]:
a+c

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [72]:
c=array([[10],[20],[30]])

In [73]:
b+c

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [74]:
c*b

array([[ 10,  20,  30,  40],
       [ 20,  40,  60,  80],
       [ 30,  60,  90, 120]])

Покомпонентное сравнение массивов

In [75]:
x=arange(-2,3)

In [76]:
x

array([-2, -1,  0,  1,  2])

In [77]:
y=-x

In [78]:
y

array([ 2,  1,  0, -1, -2])

In [79]:
maximum(x,y)

array([2, 1, 0, 1, 2])

In [80]:
minimum(x,y)

array([-2, -1,  0, -1, -2])

In [81]:
maximum(x,0)

array([0, 0, 0, 1, 2])

In [82]:
minimum(y,0)

array([ 0,  0,  0, -1, -2])

In [83]:
x>y

array([False, False, False,  True,  True])

In [84]:
x==y

array([False, False,  True, False, False])

МАКСИМУМЫ И МИНИМУМЫ 

In [85]:
a=array([[10,50,30],[60,20,40]])

In [86]:
a

array([[10, 50, 30],
       [60, 20, 40]])

In [87]:
a.max()

60

In [88]:
a.min()

10

In [89]:
a.max(0)

array([60, 50, 40])

In [90]:
a.min(1)

array([10, 20])

СОРТИРОВКА

Сортировка массива производится с помощью двух функций argsort и sort

Функция argsort производит сортировку массива и возвращает индексы отсортированных элементов. В зависимости от выбранного параметра 0 или 1 сортировка производится по столбцам или строкам соответственно. Функция sort возвращает массив отсортированных элементов

In [91]:
a=array([[10,50,30],[60,20,40]])

In [92]:
sort(a,0)

array([[10, 20, 30],
       [60, 50, 40]])

In [93]:
sort(a,1)

array([[10, 30, 50],
       [20, 40, 60]])

In [94]:
argsort(a,0)

array([[0, 1, 0],
       [1, 0, 1]])

In [95]:
argsort(a,1)

array([[0, 2, 1],
       [1, 2, 0]])

# Задания


### Создать массив  А путем создания последовательности элементов с -2 до 11 с шагом 4 

#### Создать массив  B путем создания последовательности элементов размерностью 4 элемента с -2 до 8 

### Отсортировать массив, полученный путем покомпонентного умножения элементов по возрастанию по столбцам

### Отсортировать массив, полученный путем покомпонентного сложения элементов по возрастанию по строкам с выводом индексов отсортированных элементов